FROM ghcr.io/cyber-dojo-languages/groovy:a7445f4
LABEL maintainer=jon@jaggersoft.com

ARG VERSION=4.0.23

RUN mkdir /groovy

COPY spock-core-2.4-M1-groovy-4.0.jar /groovy/

RUN cp /groovy-${VERSION}/lib/groovy-${VERSION}.jar       /groovy/
RUN cp /groovy-${VERSION}/lib/hamcrest-core-1.3.jar       /groovy/
RUN cp /groovy-${VERSION}/lib/junit-4.13.2.jar              /groovy/

ENV CLASSPATH=/groovy/

COPY red_amber_green.rb /usr/local/bin
