FROM ghcr.io/cyber-dojo-languages/groovy:d49c401
LABEL maintainer=jon@jaggersoft.com

ARG VERSION=5.0.0

RUN mkdir /groovy

COPY spock-core-2.4-groovy-5.0.jar /groovy/

RUN cp /groovy-${VERSION}/lib/groovy-${VERSION}.jar       /groovy/
RUN cp /groovy-${VERSION}/lib/hamcrest-core-1.3.jar       /groovy/
RUN cp /groovy-${VERSION}/lib/junit-4.13.2.jar            /groovy/

ENV CLASSPATH=/groovy/

